[pytest]
addopts = --reruns 0 --reruns-delay 0 -n auto

markers=
    smoke_test : this is for checking if build is ready for further testing
    data_quality : this is the data quality test
    data_extraction : data extraction related test
    data_transformation : data transformation related test
    regression_test : regresion test case